@startuml


User -> CC: cf create service
activate CC
activate Broker
CC -> Broker: Provision
Broker -> git: templates provision push
Broker -> git: secrets provision push: hang
activate git
User <- CC: provision timeout (60s)
deactivate CC

User -> CC: cf delete-service
activate CC
activate Broker
CC -> Broker: DeProvision
activate git
Broker -> git: secrets delete missing file & push
deactivate git
deactivate CC
deactivate Broker


Broker <- git: secrets provision push: complete
deactivate git
deactivate Broker

@enduml
