
security:
  user:
    password: secret

servicebroker:
  catalog:
    services:
    - id: cassandra-ondemand-service
      name: cassandra-ondemand
      description: On demand cassandra dedicated clusters
      bindable: true
      plans:
        - id: cassandra-ondemand-plan
          name: default
          description: This is a default ondemand plan.  All services are created equally.
      tags:
        -ondemand
        -document
      metadata:
        displayName: ondemand
        imageUrl: https://orange.com/image.png
        longDescription: ondemand Service
        providerDisplayName: Orange
        documentationUrl: https://orange.com/doc
        supportUrl: https://orange.com/support
        
logging:
  level:
    org.springframework.cloud.servicebroker: info
#    com.orange.oss.cloudfoundry.broker.opsautomation.ondemandbroker.git: debug
#    org.springframework.boot.context.properties.ConfigurationPropertiesBindingPostProcessor: debug
#    org.springframework.boot.bind.PropertiesConfigurationFactory: trace


