# Java Maven CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-java/ for more details
#
version: 2
jobs:
  build:
    working_directory: ~/cf-ops-automation-broker
    docker:
      - image: circleci/openjdk:8-jdk
    steps:
      - checkout
      - attach_workspace:
          at: ~/cf-ops-automation-broker
      - run:
          name: Build
          command: |
            mvn -q install:help --settings settings.xml
            mvn install --settings settings.xml
      - run:
          name: Save test results
          command: |
            mkdir -p ~/junit/
            find . -type f -regex ".*/target/surefire-reports/.*xml" -exec cp {} ~/junit/ \;
          when: always
      - store_test_results:
          path: ~/junit
      - store_artifacts:
          path: cf-ops-automation-cloudflare-broker/target/cf-ops-automation-cloudflare-broker-0.0.1-SNAPSHOT.jar
      - persist_to_workspace:
          root: .
          paths:
            - cf-ops-automation-cloudflare-broker/target/cf-ops-automation-cloudflare-broker-0.0.1-SNAPSHOT.jar
  build_n_deploy_to_bintray:
    working_directory: ~/cf-ops-automation-broker
    docker:
      - image: circleci/openjdk:8-jdk
    steps:
      - checkout
      - attach_workspace:
          at: ~/cf-ops-automation-broker
      - run:
          name: deploy snapshots to bintray
          command: bin/deploy_to_bintray.sh
      - run:
          name: Save test results
          command: |
            mkdir -p ~/junit/
            find . -type f -regex ".*/target/surefire-reports/.*xml" -exec cp {} ~/junit/ \;
          when: always
      - store_test_results:
          path: ~/junit
      - store_artifacts:
          path: cf-ops-automation-cloudflare-broker/target/cf-ops-automation-cloudflare-broker-0.0.1-SNAPSHOT.jar
      - store_artifacts:
          path: ~/tmp/JFrogPromotion.url
      - persist_to_workspace:
          root: .
          paths:
            - cf-ops-automation-cloudflare-broker/target/cf-ops-automation-cloudflare-broker-0.0.1-SNAPSHOT.jar
            - bin/release.sh
            - tmp/JFrogPromotion.url
  release_to_bintray:
    working_directory: ~/cf-ops-automation-broker
    docker:
      - image: circleci/golang:1.8.1
    steps:
      - attach_workspace:
          at: ~/cf-ops-automation-broker
      - run:
          name: release to bintray
          command: bin/release.sh
  release_to_github:
    working_directory: ~/cf-ops-automation-broker
    docker:
      - image: circleci/golang:1.8.1
    steps:
      - attach_workspace:
          at: ~/cf-ops-automation-broker
      - run:
          name: release artefact to github
          command: cf-ops-automation-cloudflare-broker/bin/release.sh github_api_token=$GITHUB_TOKEN owner=$CIRCLE_PROJECT_USERNAME repo=$CIRCLE_PROJECT_REPONAME tag=$CIRCLE_TAG filename=./cf-ops-automation-cloudflare-broker/target/cf-ops-automation-cloudflare-broker-0.0.1-SNAPSHOT.jar
workflows:
  version: 2
  build-n-deploy:
    jobs:
      - build:
          filters:
            branches:
              ignore: develop
      - build_n_deploy_to_bintray:
          filters:
            branches:
              only: develop
            tags:
              only: /.*/
      - release_to_bintray:
          requires:
            - build_n_deploy_to_bintray
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /.*/
