---
director_uuid: "xxxxx"
name: "hazelcast"
releases:
- name: "hazelcast"
  version: "latest"
- name: "consul"
  version: "latest"
- name: "logsearch-shipper"
  version: "latest"
- name: "route-registrar"
  version: "latest"
update:
  canaries: 0
  canary_watch_time: "30000-240000"
  update_watch_time: "30000-240000"
  max_in_flight: 1
  serial: false
stemcells:
- alias: "trusty"
  os: "ubuntu-trusty"
  version: "latest"
instance_groups:
- name: "hazelcast-management"
  instances: 1
  vm_type: "default"
  stemcell: "trusty"
  azs:
  - "z1"
  networks:
  - name: "net-hazelcast"
  jobs:
  - name: "broker"
    release: "hazelcast"
    consumes: {}
    provides: {}
    properties: {}
  - name: "hazelcast_mancenter"
    release: "hazelcast"
    consumes: {}
    provides: {}
    properties: {}
  - name: "route-registrar"
    release: "route-registrar"
    consumes: {}
    provides: {}
    properties:
      route_registrar:
        external_host: "elpaaso-hz-mancenter.cw-vdr-api.redacted-domain.org"
        port: 9000
        message_bus_servers:
        - host: "192.168.131.6:4222"
          user: "nats"
          password: "wwwwww"
        health_checker:
          interval: 10
          name: "healthchk"
  properties: {}
- name: "consul-servers"
  instances: 3
  vm_type: "default"
  stemcell: "trusty"
  persistent_disk_type: "small_disk"
  azs:
  - "z1"
  networks:
  - name: "net-hazelcast"
  jobs:
  - name: "consul"
    release: "consul"
    consumes: {}
    provides: {}
    properties:
      consul:
        join_hosts:
        - "192.168.171.39"
        - "192.168.171.40"
        - "192.168.171.41"
        default_recursor: "185.23.94.244"
        domain: "consul"
        server: true
        user: "vcap"
      networks:
        apps: "net-hazelcast"
  properties: {}
- name: "hazelcast-cluster"
  instances: 2
  vm_type: "default"
  stemcell: "trusty"
  persistent_disk_type: "small_disk"
  azs:
  - "z1"
  networks:
  - name: "net-hazelcast"
  jobs:
  - name: "consul"
    release: "consul"
    consumes: {}
    provides: {}
    properties:
      consul:
        join_hosts:
        - "192.168.172.39"
        - "192.168.171.40"
        - "192.168.171.41"
        server: false
        user: "vcap"
      networks:
        apps: "net-hazelcast"
  - name: "hazelcast_node"
    release: "hazelcast"
    consumes:
      peers: {}
    provides:
      peers: {}
    properties:
      hazelcast:
        jvm:
          memoryMo: 3000
        group:
          name: "hz-group"
          password: "wwwwwwwwwwwwwww"
  properties: {}
properties:
  logsearch:
    logs:
      server: "logsearch-dfy:5514"
