security:
  user:
    password: secret

servicebroker:
  catalog:
    services:
    - id: cloudflare-route
      name: cloudflare
      description: Creates a internet domain protected by cloudflare.
      bindable: false
      planUpdateable: false
      plans:
        - id: cloudflare-default
          name: default
          description: Single default plan.
      tags:
        -ondemand
        -document
      metadata:
        displayName: cloudflare
        imageUrl: https://upload.wikimedia.org/wikipedia/en/thumb/a/a2/Cloudflare_logo.svg/1200px-Cloudflare_logo.svg.png
        longDescription: Creates an internet-facing domain protected by cloudflare DOS prevention, and potentially other features such as analytics, rate limiting. try syntax: cf cs cloudflare default myroute2 -c '{"route-prefix":"myroute2"}' which should result into a new route without hostname created in the current space. This route needs to be bound applications.
        providerDisplayName: Orange
        documentationUrl: https://orange.com/doc
        supportUrl: https://orange.com/support
logging:
  level:
    com.orange.oss: debug
    org.springframework.cloud.servicebroker: debug

