---
resource_types:
- name: slack-notification
  type: docker-image
  source:
    repository: cfcommunity/slack-notification-resource
    tag: "1.6.0"

resources:
- name: hourly
  type: time-resource
  source:
    start: 06:00
    stop: 22:00
    interval: 1h
    location: "Europe/Paris"

- name: failure-alert
  type: slack-notification
  source:
    url: ((slack-webhook))
    proxy: ((slack-proxy))
    proxy_https_tunnel: ((slack-proxy-https-tunnel))
    disable: ((slack-disable))

- name: cf-ops-automation
  type: git
  source:
    uri: https://github.com/orange-cloudfoundry/cf-ops-automation
    branch: master
    tag_filter: ""
    skip_ssl_verification: true

jobs:
- name: cleanup-coab-deployments
  on_failure:
    put: failure-alert
    params:
      channel: ((slack-channel))
      text: Failed to run [[$BUILD_PIPELINE_NAME/$BUILD_JOB_NAME ($BUILD_NAME)]($ATC_EXTERNAL_URL/teams/main/pipelines/$BUILD_PIPELINE_NAME/jobs/$BUILD_JOB_NAME/builds/$BUILD_NAME)].
      icon_url: http://cl.ly/image/3e1h0H3H2s0P/concourse-logo.png
      username: Concourse
  plan:
  - in_parallel:
    - get: cf-ops-automation
      params: { submodules: none}
      attempts: 2
    - get: hourly
      trigger: true
  - task: generate-flight-plan
    output_mapping: {result-dir: delete-plan}
    config:
      platform: linux
      image_resource:
        type: docker-image
        source: {repository: concourse/busyboxplus, tag: "git"}
      outputs:
        - name: result-dir
      run:
        path: sh
        args:
        - -ec
        - |
          echo "trigger-job -j $BUILD_PIPELINE_NAME/approve-and-delete-disabled-deployments" | tee -a result-dir/flight-plan
      params:
        BUILD_PIPELINE_NAME: coab-depls-bosh-generated
  - task: fly-into-concourse
    input_mapping: {fly-cmd: delete-plan}
    output_mapping: {flight-report: concourse-delete-report}
    file: cf-ops-automation/concourse/tasks/fly_execute_commands.yml
    params:
      ATC_EXTERNAL_URL: ((concourse-target))
      FLY_USERNAME: ((concourse-username))
      FLY_PASSWORD:  ((concourse-password))
      FLY_TEAM: ((concourse-team))
